# Generated by Django 4.2.13 on 2024-05-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='chromebook_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='loan_date',
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromebook_number', models.CharField(max_length=255)),
                ('borrowed_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaner.student')),
            ],
        ),
    ]
